# Generated by Django 3.0.5 on 2020-05-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlisttechnique',
            name='order',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
