# Generated by Django 3.0.5 on 2020-05-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technique',
            name='description',
            field=models.CharField(default='To be added..', max_length=1000),
        ),
        migrations.AlterField(
            model_name='technique',
            name='instructions',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='technique',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
