# Generated by Django 3.0.5 on 2020-05-03 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technique',
            old_name='author',
            new_name='user',
        ),
    ]
