# Generated by Django 3.0.5 on 2020-05-03 04:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_auto_20200502_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='technique',
        ),
        migrations.AddField(
            model_name='favorites',
            name='technique',
            field=models.ManyToManyField(to='main_app.Technique'),
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='user',
        ),
        migrations.AddField(
            model_name='favorites',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
