# Generated by Django 3.0.5 on 2020-05-03 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200503_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technique',
            name='user',
        ),
    ]
