# Generated by Django 3.0.5 on 2020-05-03 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_technique_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='technique',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.Profile'),
        ),
    ]
