# Generated by Django 3.0.5 on 2020-05-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200504_0000'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JoinPlaylist',
            new_name='PlaylistTechnique',
        ),
        migrations.AddField(
            model_name='playlist',
            name='techniques',
            field=models.ManyToManyField(through='main_app.PlaylistTechnique', to='main_app.Technique'),
        ),
    ]
