# Generated by Django 3.0.5 on 2020-05-04 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200504_0100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Followings',
            new_name='Following',
        ),
        migrations.AlterField(
            model_name='following',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='main_app.Profile'),
        ),
        migrations.AlterField(
            model_name='following',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='main_app.Profile'),
        ),
    ]
