# Generated by Django 3.0.5 on 2020-05-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlisttechnique',
            name='time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_url',
            field=models.URLField(default='https://source.unsplash.com/random/30x50'),
        ),
    ]
