# Generated by Django 3.0.5 on 2020-05-05 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20200505_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlisttechnique',
            old_name='time',
            new_name='duration',
        ),
    ]
